### ISSUE TITLE
Idea regarding the "greeting" message?

### ISSUE THREAD

**Issue by rosalieb** [robertladwig/LakeModelR#3]
Not an issue but an idea I had when I saw the greeting message "What a beautiful day to run a lake model."!
(oh no, is it the GitHub version of conferences' "I have more of a comment than a question")...

Since it appears that the tool has vocation to be educational too, you could have different greeting messages coming in. To achieve that, you could have a table with as many rows as potential messages. For example:

|             greet   |    bye              |
|----------------|----------------|
|"What a beautiful day to run a lake model." | "Have a lovely rest of your day!"|
|"What is the deepest lake in the world?" | "Lake Baikal (5,315 feet [1,620 meters])"|

If you define the table above in your script, you could sample in this dataframe a row from the "greet" table to have several messages every time the model is run?
I forked your repo and edited the script to explain the idea if you end up wanting to do that...

Good job, this is a great tool!

**Comment by robertladwig** [comment]
I love that idea! Can you do a PR please @rosalieb ?

**Comment by rosalieb** [comment]
Done!

**Comment by robertladwig** [comment]
Thanks!
