### ISSUE TITLE
Can't find k600.2.kGAS.base() - Issue when trying to run the model with water quality

### ISSUE THREAD

**Issue by rosalieb** [robertladwig/LakeModelR#5]
When water.quality = TRUE in run_thermalmodel(), I get the message:

Error in k600.2.kGAS.base(k.vachon.base(wnd = WIND, lake.area = max(AREA)),  : 
  could not find function "k600.2.kGAS.base"

**Comment by robertladwig** [comment]
You'd need to install library(LakeMetabolizer)
`install.packages('LakeMetabolizer')`
I used functions from there to create custom algorithm for oxygen.

**Comment by rosalieb** [comment]
oops sorry I went too fast. Yep it works now!
